### ISSUE TITLE
2.0.5: [vue-i18n-extract] Error: vueFiles glob has no files.

### ISSUE THREAD

**Issue by Cyclodex** [Spittal/vue-i18n-extract#159]
Since today, my _npm run script_ is not working anymore, it throws a error about `vueFiles glob has no files.`.

I see there was a release 2.0.5 yesterday.
2.0.4 works perfectly fine.

My config file has:
`vueFiles: "./src/**/*.?(ts|js|vue)",`

Did you change something on the files matcher since 2.0.4?

![image](https://user-images.githubusercontent.com/840929/165693906-336d9f2f-83f9-402f-a8d2-6f4aa6d8c4db.png)

My workaround for now is, to execute your 2.0.4 version:
`"i18n:reportDeOnly": "npx vue-i18n-extract@2.0.4 --languageFiles ./src/locales/de-CH.json",`

**Comment by Spittal** [comment]
I didn't specifically, but I did update the glob package which might have changed the syntax?

**Comment by frynt** [comment]
Same problem with `2.0.5` and `2.0.6` version

**Comment by mreduar** [comment]
Same problem here

**Comment by hk67393309** [comment]
> Since today, my _npm run script_ is not working anymore, it throws a error about `vueFiles glob has no files.`.
> 
> I see there was a release 2.0.5 yesterday. 2.0.4 works perfectly fine.
> 
> My config file has: `vueFiles: "./src/**/*.?(ts|js|vue)",`
> 
> Did you change something on the files matcher since 2.0.4?
> 
> ![image](https://user-images.githubusercontent.com/840929/165693906-336d9f2f-83f9-402f-a8d2-6f4aa6d8c4db.png)
> 
> My workaround for now is, to execute your 2.0.4 version: `"i18n:reportDeOnly": "npx vue-i18n-extract@2.0.4 --languageFiles ./src/locales/de-CH.json",`

2.0.4 use glob ^7.1.6, 2.0.6 use glob ^8.0.1

**Comment by hk67393309** [comment]
but use glob separate no problem.
![1111](https://user-images.githubusercontent.com/77831943/168410995-d3fafa81-d647-4f90-8f0a-5eeb07feeb91.png)

**Comment by kleinfreund** [comment]
I think I have a theory that explains these issues.

The call to `glob.sync(src)` (https://github.com/Spittal/vue-i18n-extract/blob/main/src/create-report/vue-files.ts#L11) receives the result of `path.resolve(process.cwd(), vueFilesGlob)` (https://github.com/Spittal/vue-i18n-extract/blob/9680c12b53061cff8553d3551ec4cddf622f4604/src/create-report/index.ts#L24) where `vueFilesGlob` is something like `"./src/**/*.?(js|vue)"`. Combined, the call is effectively something like this:

```js
require('glob').sync(
  require('path').resolve(process.cwd(), "./src/**/*.?(js|vue)")
)
```

According to [node-glob: changelog.md: 8.0](https://github.com/isaacs/node-glob/blob/main/changelog.md#80):

> Glob pattern paths must use forward-slashes as path separators, since \ is an escape character to match literal glob pattern characters.

On Windows, the following _will_ result in a string containing two backslashes as path separators (i.e. `\\` instead of `/`):

```js
require('path').resolve(process.cwd(), "./src/**/*.?(js|vue)")
```

A naive fix for this could be to add something like `.replace(/\\/g, '/')` to the path before passing it to `glob.sync`.

I’m happy to file a pull request for this if that is indeed the case.

**Comment by mreduar** [comment]
I am sorry to say that this problem has not yet been solved on Windows with the latest version `2.0.7`. Only works from npx command

**Comment by kleinfreund** [comment]
> I am sorry to say that this problem has not yet been solved on Windows with the latest version `2.0.7`.

@mreduar What’s the issue that’s occurring for you? Do you get any error messages?

**Comment by mreduar** [comment]
> @mreduar What’s the issue that’s occurring for you? Do you get any error messages?

Yes, the error message is as follows.

```
> vue-i18n-extract report --vueFiles './resources/js/**/*.vue' --languageFiles './lang/js/*.json' --add --remove --noEmptyTranslation=*

[vue-i18n-extract] Error: vueFiles glob has no files.
    at readVueFiles (C:\Users\Eduar\Projects\my_project\node_modules\vue-i18n-extract\dist\vue-i18n-extract.umd.js:83:13)
    at createI18NReport (C:\Users\Eduar\Projects\my_project\node_modules\vue-i18n-extract\dist\vue-i18n-extract.umd.js:338:22)
    at CAC.<anonymous> (C:\Users\Eduar\Projects\my_project\node_modules\vue-i18n-extract\bin\vue-i18n-extract.js:47:5)
    at CAC.runMatchedCommand (C:\Users\Eduar\Projects\my_project\node_modules\cac\dist\index.js:614:34)
    at CAC.parse (C:\Users\Eduar\Projects\my_project\node_modules\cac\dist\index.js:541:12)
    at Object.<anonymous> (C:\Users\Eduar\Projects\my_project\node_modules\vue-i18n-extract\bin\vue-i18n-extract.js:56:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

It should be noted that I have to use this command, because if I use it the way the readme example (with `*.?(js|vue)` and `*.?(json|yml|yaml|js)`) says it doesn't work either.
`"vue)'" is not recognized as an internal or external command.` is the error if I use it with the regular expression in that way

**Comment by kleinfreund** [comment]
@mreduar Hey there,

After `dist/vue-i18n-extract.umd.js:73`, can you add `console.log({ src, normalizedSrc })` and run the following (the same command you used above):

```sh
node ./bin/vue-i18n-extract.js report --vueFiles ./tests/fixtures/vue-files/Basic.vue --languageFiles './tests/fixtures/lang/**/*.?(json)'
```

On my machine, the two paths logged are these (I use Ubuntu):

```js
{
  src: '/home/phil/dev/packages/vue-i18n-extract/tests/fixtures/vue-files/Basic.vue',
  normalizedSrc: '/home/phil/dev/packages/vue-i18n-extract/tests/fixtures/vue-files/Basic.vue'
}
```

In your case, I would expect the two to look like this:

```js
{
  src: 'C:\\Users\\Eduar\\Projects\\my_project\\node_modules\\vue-i18n-extract\\tests\\fixtures\\vue-files\\Basic.vue',
  normalizedSrc: 'C:/Users/Eduar/Projects/my_project/node_modules/vue-i18n-extract/tests/fixtures/vue-files/Basic.vue'
}
```

If that is indeed the result that you’re getting, can you please tell us which version of `glob` is installed in your project (i.e. check the `version` field in the `node_modules/glob/package.json` file). Mine is v8.0.3.

In case this doesn’t lead to any useful results, you can also try and perform like this some specific tests around the glob package by running `node` in a terminal and then import the package and running `glob.sync` manually like this:

```node
const glob = require('glob')
glob.sync('C:/Users/Eduar/Projects/my_project/node_modules/vue-i18n-extract/tests/fixtures/vue-files/Basic.vue')
```

That *should* yield results.

**Comment by mreduar** [comment]
I suspected it from the beginning, but I wasn't sure since I have no experience with javascript packages. My suspicion was that the files inside `dist` folder were not updated with respect to the changes you made in PR #166, so `normalizedSrc` is not an existing variable in the `dist/vue-i18n-extract.umd.js` file. It's only available in `src\create-report-vue-files.ts`, so I did a compile with `npm run build` and now the files are updated and I don't get the error and the console prints the files correctly and this is the console.log output
```
{
  src: 'C:\\Users\\Eduar\\Projects\\vue-i18n-extract\\tests\\fixtures\\vue-files\\Basic.vue',
  normalizedSrc: 'C:/Users/Eduar/Projects/vue-i18n-extract/tests/fixtures/vue-files/Basic.vue',
  targetFiles: [
    'C:/Users/Eduar/Projects/vue-i18n-extract/tests/fixtures/vue-files/Basic.vue'
  ]
}
```

**Comment by kleinfreund** [comment]
@mreduar Aha! That explains it. Yes, the files in the `dist` directory of the project have not been re-built. This should probably be done to simplify local development processes.

That means the fix is working for you then?

**Comment by mreduar** [comment]
@kleinfreund Yes, the solution in PR #166 works if I do the compilation in the package, however in the project I am using the package does not work as it needs to have the latest changes in dist I guess. 
So it will be to send another PR with the compilation with the latest changes or have @Spittal do it.

**Comment by kleinfreund** [comment]
@mreduar I filed another PR for addressing this: https://github.com/Spittal/vue-i18n-extract/pull/170

**Comment by mreduar** [comment]
Thank you so much @kleinfreund!

**Comment by woncode** [comment]
I also meet this error in version 2.0.7，I'm use windows 10.
my cmd is `vue-i18n-extract report --vueFiles 'src/views/**/*.?(vue)' --languageFiles 'src/lang/zh.json'`

I log the path as below
![image](https://user-images.githubusercontent.com/20252778/184596427-827f0cb0-a34f-4d8c-9b53-0986647e18f7.png)

and find it become as below
![image](https://user-images.githubusercontent.com/20252778/184596733-90d368d4-f185-42d2-b605-55e67055ee7d.png)

so, fix this error need remove the quotation mark for vueFiles and languageFiles argument.

this cmd will work: `vue-i18n-extract report --vueFiles src/views/**/*.?(vue) --languageFiles src/lang/zh.json`

**Comment by diengv** [comment]
my window 11:  fix done
`vue-i18n-extract report --noEmptyTranslation=\"*\" --add true --vueFiles=\"./src/**/*.?(vue|ts)\" --languageFiles=\"./src/locales/*.json\"`

**Comment by dadyday** [comment]
Will not work on windows.
Please fix: `src = src.replace(/\\/g, '/');`  in readLanguageFiles(src) and readVueFiles(src)

**Comment by fatih-koc** [comment]
Please fix this issue. We are not able to define multiple folders or a single /src folders.
